course = "iam not looking for forgivenss am the demon"
print(course[-1])
print(course[0])
print(course[-5])
print(course[-4])
print(course[-3])
print(course[-8])
print(course[3])
print(course[0:6])
print(course[0:8])
print(course[0:15])
print(course[0:-10])
print(course[0:16])
print(course[0:-8])
print(course[0:])
print(course[:6])
course1 = ' why so serious'
steve = ' i can do this all day'
another = course[:]
print(course[:])
print(course[1:-1])
print(course[1:-6])
print(course[0:-3])
print(course[0:8])
print(steve.replace("a", "i"))
print(steve.replace("n", "d"))
print(steve.replace("y", "o"))
print(steve.replace("i", "r"))
print(steve)
print(course + course1 + steve)
